### ISSUE TITLE
Problems restoring VM from memory 

### ISSUE THREAD

**Issue by crodnun** [howerj/embed#1]
[embed.c.txt](https://github.com/howerj/embed/files/1952043/embed.c.txt)
[vm.c.txt](https://github.com/howerj/embed/files/1952044/vm.c.txt)

Hi Richard, we have started to integrate EMBED in our project and have some issues when we save VM into memory and then try to reuse it again (loading again from memory).

I share with you here our codes so far (vm.c is our interface that calls the embed.c routines), this module wraps the forth_t inside another type called VirtualMachine_t, just to make things easier but it is just a wrapper.

I have created a new function at embed called embed_eval() just to mimic what embed_forth() does but this time using an input string and recovering VM output in out buffer (instead of using stdin/stdout).

Apart I have created just a couple of functions to create a VM from memory or to memcpy it into memory (this chunk of bytes is what we store at DB).

Also I have integrated embed.c with our engine_trace() function to display log info.

The things go fine when we create the VM for the first time, we can run the first command and retrieve the output. We receive even the first lines of the VM prompt/console.

Then we store the full VM struct (forth_t) into memory (once this first command is executed).

After a while we retrieve this chunk of memory and try to run a different command, using embed_eval() again with the VM loaded from memory.

At this point we got stalled, the VM keeps answering always the same result (the answer to the first command we issued), regardless input command, seems that it keeps in the same state or does not save something before finishing.

Hope you can give us a hint of why it is happening this, thanks a lot 
Carlos

**Comment by howerj** [comment]
Hi! I'll look into it tonight, I've notice a few things already, some not to do with your problems but could potentially cause other issues.

For now a quick fix should be to do the following. In VM instruction 24 instead of setting "T = EOF", goto finished instead. This is because the Forth interpreter checks for EOF and eventually calls instruction 27 which is normally correct, but this will mess things up for you. You also need to make sure that you append a space after each evaluated string. This is a temporary fix, but should work.

**Comment by howerj** [comment]
You'll also need to do a 'pc--' before the goto. And I'll keep you posted if I think of anything else.

**Comment by howerj** [comment]
Actually, that's not quite true, you need to save the old PC value before this line occurs "pc = instruction & 0x10 ? m[rp] >> 1 : pc + 1;" and restore that before the goto.

**Comment by howerj** [comment]
I've made a custom version of 'embed' with some of your changes in it, type 'make run' to build and run it. In 'main.c' there are two calls to the evaluator, and in 'embed' you can see the needed changes to 'embed_eval'.

[custom-embed.tar.gz](https://github.com/howerj/embed/files/1952535/custom-embed.tar.gz)

**Comment by crodnun** [comment]
Thanks a lot Richard, this version solves the issue we had and after the first tests, everything now goes fine when recovering the VM from memory, one more question. How we could disable the initial prompt returned by the VM when user executes the very first instruction:

eFORTH V 1984
 157E 2A82

It does not make sense when running from our engine.
Again, thanks.
Carlos

**Comment by howerj** [comment]
I've made a few changes to the Forth interpreter which means old images will not work with the new ones and the interpreter needs updating. This should help things moving forwarding, if you don't want these changes you can use commits "9715d5f1fecf7d315968f3bc03e736749647a62b" and prior. These changes include saving the return, variable, program counter and top of stack variables in locations in the virtual machine so they can be restored. I can help integrating the new VM/image if you need.

To remove the prompt you will need to build a new image with the metacompiler and then use the new image. You need to modify 'meta.fth' so the line defining 'hi' is changed, it currently is:

        h: hi hex cr ." eFORTH V " ver 0 u.r cr here . .free cr [ ; ( -- )

This needs to be changed to:

       h: hi hex [ ; ( -- )

You can also remove the 'ok' prompt by setting:

         h: (ok) command? if ."  ok  " cr exit then ;  ( -- )

To:
     h: (ok)  ;  ( -- )

And rebuilding the 'meta1.blk' image, and use this new image as a starting point.

**Comment by howerj** [comment]
Hi, did this work? I'm going to close the issue if it did.
Thanks.

**Comment by crodnun** [comment]
Yes Richard, now it works as we expected when recovering VM from memory. Feel free to close the issue and again, thanks a lot for your help!
