### ISSUE TITLE
Port to Raspberry Pi Pico?

### ISSUE THREAD

**Issue by znmeb** [howerj/embed#11]
I'm thinking about porting this to a Raspberry Pi Pico. I'm not opposed to a 16-bit Forth, but the Pico is a 32-bit machine (264Kbytes RAM, 2 Mbytes flash, Arm Cortex M0+). How difficult would it be to do this port?

**Comment by howerj** [comment]
It should be fairly easy to do if you're familiar with Forth. I agree, 16-bit Forth implementations are limiting, but I tend to only use Forth for fun, in which case 16-bit Forths are optimal. I take it you would target the ARM instruction set directly, as porting the C program would be trivial? 

A lot of the code in the meta-compiler is agnostic to the word size, but there might be a few dependencies on it that that trip you up. I'd start with a blank file and copy bits of the meta-compiler and program across bit by bit.

**Comment by znmeb** [comment]
> It should be fairly easy to do if you're familiar with Forth. I agree, 16-bit Forth implementations are limiting, but I tend to only use Forth for fun, in which case 16-bit Forths are optimal. I take it you would target the ARM instruction set directly, as porting the C program would be trivial?

The Pico has a CMake / GCC cross-compile and cross-link SDK. It's designed to run on a Raspberry Pi but it also works in Windows Subsystem for Linux in Debian "bullseye" and Ubuntu "focal". So my initial plan was to make the C virtual machine work with 32-bit cells and addresses on a 32-bit Raspberry Pi, get the whole thing working on the Pi and then rebuild for the Pico.

I do want a "thumb" assembler in the final version but an initial C token-threaded inner interpreter is fine to start with.

I'm not opposed to a 16-bit Forth, but I want the final version to be able to interoperate with 32-bit C libraries, especially FreeRTOS and LittleFS.

**Comment by howerj** [comment]
That makes sense, and should be doable, I think that's a sensible plan.
