### ISSUE TITLE
Having trouble connecting Embed commands to C routines

### ISSUE THREAD

**Issue by darozak** [howerj/embed#3]
Hi Richard,

Carlos has been having trouble getting the "Call" demo to work. The concept for how to integrate FORTH commands with the surrounding C environment makes perfect sense but we're just not getting the the expected results.  Can you provide guidance on how we can get things working properly on our end?

Dave

**Comment by howerj** [comment]
Sure! Do you mean the 'call.c' demo application in the embed repository? If so, do you mean you are having trouble running some Forth that exercises the new floating point routines that 'call.c' creates? I don't think I included any example code, so it might be a little tricky to work out how to use the newly defined routines yourself.

To enter floating point number use 's>f' to convert an integer into a floating point number, then you can do floating point operations on that number, like so:

   4 s>f fdup f+ f. ( this should print 8.000000e+00 )

Or:

  2 s>f fsqrt f. ( prints 1.414214e+00 )

This calls into the newly defined words, defined in 'call.c', which are written in C and accessed by the CALL VM instruction.

Is this what you mean? Or do you mean how the 'call.'c program actually works?

**Comment by crodnun** [comment]
Thanks Richard, that's what we exactly mean, just some quick examples of how we can use the float point operations. The tricky part was the conversion from integer to float numbers, that was a headache for us, now crystal clear, thanks.

**Comment by howerj** [comment]
Okay, I'll close this then!
