### ISSUE TITLE
Doubt regarding embed image

### ISSUE THREAD

**Issue by crodnun** [howerj/embed#7]
Hi Richard, hope everything is fine at your side.
Do you remember us? We were working with your embed project a long time ago, lol.
So far, so good. But now we need to go a step forward and define inside the FORTH virtual machine new words for our own purposes (default words).

We have tried these steps:

1- Modify the embed.fth file, adding this line:

```
: 2drop drop drop ;         ( n n -- )
: 1+ 1 + ;                  ( n -- n : increment a value  )
: 2+ 2 + ;                  ( n -- n : increment a value by two )     <---- This is new, added by us
```

Then running:

```
./embed -o newvm.blk embed.fth 
FORTH META COMPILATION START 
COMPILATION COMPLETE
HOST:    3F48
TARGET:  1528
HEADER: 
  5000:     14     0  7FFF  2400   347  8000     0    14  _______$G_______
  5010:      0  7FFF  2400  4689  4854   A0D   A1A  1528  _____$_FTH____(_
  5020:   4DEA     1  1984     1   949  628D  601C  628D  _M______I__b_`_b
  5030:   631C  10E0  151E     0  7003  6461  4017  4100  _c_______pad_@_A
SAVING...DONE
STACK> <sp
```

We generate a new VM with this new word.

The problem we find is that this new VM image seems to not contain our word **2+**.

Are we doing it correctly? Could you share some quick guidance on the steps required otherwise?
Thanks in advance and best regards.
Carlos & Dave

**Comment by howerj** [comment]
Hello! I do remember, yes!

Can you tell me the commit that you are using? If I do this on master, commit ID e1c1274f6898866e0e2f71d5f16252fef8f3ee5c, and I add the definition of '2+' on line 1119, then type 'make run', the new definition appears in the dictionary in the newly generated image. 

In fact if you type 'make run' on the master it is rebuilding and the entire image as a sort of test before hand.  You can see this here:

```
./embed -o embed-1.blk embed.fth
FORTH META COMPILATION START 
COMPILATION COMPLETE
HOST:    3F40
TARGET:  1526
HEADER: 
  5000:     14     0  7FFF  2400   34D  8000     0    14  _______$M_______
  5010:      0  7FFF  2400  4689  4854   A0D   A1A  1526  _____$_FTH____&_
  5020:   56ED     1  1984     1   948  628D  601C  628D  _V______H__b_`_b
  5030:   631C  10DE  151C     0  7003  6461  4017  4100  _c_______pad_@_A
SAVING...DONE
STACK> <sp

./embed -o tmp.blk -i embed-1.blk
eFORTH v1984
 5414 10970
```

Thanks,
Richard Howe

**Comment by crodnun** [comment]
Thanks, Richard, I think that we are using an old version of the project. Honestly, we do not remember when was the latest time we picked it from your repo, lol.
Maybe it is a good moment to upgrade, but let me first describe our issue in order to see together if it is something fixed lately (and makes sense to upgrade) or it is just our mistake using it.

We are using callbacks in our project, some words are directly chained to these callbacks. Right now we have these ones:

```
// x macro to manage callbacks
#define CALLBACK_XMACRO\
  X("perform",  vm_ext_execute_cb, true)\
  X("query",    vm_ext_query_cb,  true)\
  X("report",   vm_ext_report_cb, true)
```

Just 3 words that we want to treat using our C code, they work fine, no issues there.

Now, as I stated in my previous post, we want to have new words in the base image (using the meta-compiler and the embed.fth), apart from the original ones, by default we want to have a base image with some extra words. Just add more words there as a kind of "factory settings".

We have detected that if we add a new word at embed.fth and generate a new image, there is no problem. We can use both: the extensions/callbacks and the new word defined at .fth file.

As soon as we add more words at embed.fth (2 or more new definitions) and try to use the new image inside the system, we find issues/conflicts with the words defined at callbacks, maybe a problem in max size available for all them?

The error reported when loading callbacks is the following, notice that this is the first callback in the list:

```
ERROR: evaluation of statement (: perform 0 vm ; -2 cells allot ' vm chars ,
) returned -1

```

Our guess is that we need to increase memory somehow to give more space for new words, but not sure if this assumption is correct. 

We create the VM and then add the extensions, find attached the code that we use to load the extension, it was taken from your examples at call.c:

```
/** ****************************************************************************

  @brief      Adds all user defined callbacks to the VM (defining new words with 'embed_eval')

  @param[in]  vm       Current VM
  @param[in]  optimize Flag to optimize or not the word definition in memory 
  @param[in]  cb       Array of callbacks to be added
  @param[in]  number   Callbacks array size

  @return     Execution result

*******************************************************************************/
static int vm_add_callbacks(VirtualMachine_t* const vm, const bool optimize,  VmExtensionCb_t *cb, const size_t number) 
{
  // input pointers checked by calling function
  //assert(vm && cb);

  const char *optimizer = optimize ? "-2 cells allot ' vm chars ," : "";
  static const char *preamble = "only forth definitions system +order\n";
  int r = 0;

  if((r = embed_eval(vm, preamble)) < 0) {
    engine_trace(TRACE_LEVEL_ALWAYS, "ERROR: evaluation of preamble (%s) returned %d", preamble, r); 
    return r;
  }

  for(size_t i = 0; i < number; i++) {
    char line[80] = { 0 };
    if(!cb[i].use)
      continue;
    r = snprintf(line, sizeof(line), ": %s %u vm ; %s\n", cb[i].name, (unsigned)i, optimizer);
    assert(strlen(line) < sizeof(line) - 1);
    if(r < 0) {
      engine_trace(TRACE_LEVEL_ALWAYS, "ERROR: format error in snprintf (returned %d)", r); 
      return -1;
    }
    if((r = embed_eval(vm, line)) < 0) {
      engine_trace(TRACE_LEVEL_ALWAYS, "ERROR: evaluation of statement (%s) returned %d", line, r); 
      return r;
    }

    engine_trace(TRACE_LEVEL_ALWAYS, "Callback (%s) added to VM", cb[i].name); 
  }
  embed_reset(vm);
  return 0;
}
```

As soon as we define more than 1 word at base  .fth file and compile it to generate a new image, this part fails.

Thanks in advance and best regards

**Comment by howerj** [comment]
Hmmm, okay, I noticed you've forked the 'embed' project, did you take it from that point? If it is a problem with too many words being defined at the meta-compilation it's still not the end of the world. There are ways around that, but I'd like to verify that first.

It would help if you could prepare an archive that contains your version of the interpreter, image, unmodified 'embed.fth' file and your modified 'embed.fth' file and callbacks (or something that fails). That gives me something to debug at least, as I cannot see anything in the example you have provided that is wrong.

I can't respond during the day so it takes me a while to respond.

Thanks,
Richard

**Comment by crodnun** [comment]
Hi Richard, thanks a lot.
Take your time to respond, no rush at all with this please. 
I attach here as much information as possible, as requested.

Firstly the embed project version we are using so far (whole code we use now, probably an snapshot of your repo around July 2018).

[embed.tar.gz](https://github.com/howerj/embed/files/4101621/embed.tar.gz)

Typing make you can generate the embed binary, the .fth file we have used till now is the embed.fth you can find there (this has been always the meta-data for our images).

We generate the base image for our application, just using this code and typing:

```
make
embed -o embed.blk embed.fth
```

This is the output we obtain after second command:

```
# ./embed -o embed.blk embed.fth
FORTH META COMPILATION START 
COMPILATION COMPLETE
HOST:    3F34
TARGET:  151A
HEADER: 
  5000:     14     0  7FFF  2400   347  8000     0    14  _______$G_______
  5010:      0  7FFF  2400  4689  4854   A0D   A1A  151A  _____$_FTH______
  5020:   2155     1  1984     1   942  628D  601C  628D  U!______B__b_`_b
  5030:   631C  10D2  1510     0  7003  6461  4017  4100  _c_______pad_@_A
SAVING...DONE
STACK> <sp
```

Every user has his own copy of this base image as start point. Then obviously, depending on the words defined and the commands run, it evolves. We always keep track of the latest VM in binary format inside our DB (for each user).

Apart from this, we define programmatically some callbacks, every time we want to use the VM.  The callbacks defined so far are the following:

```
// x macro to manage callbacks
#define CALLBACK_XMACRO\
  X("perform",  vm_ext_execute_cb, true)\
  X("query",    vm_ext_query_cb,  true)\
  X("report",   vm_ext_report_cb, true)
```

As a summary, we do these steps:

- The first time a user uses the VM

1 - Load from file (.blk) the base image.
2 - Define programmatically the callbacks at C side and attach them to VM.
3 - Execute the requested user's command.
4 - Store the VM snapshot/image into DB (binary format).

- Next times

1 - Load into memory (from DB) the latest VM image.
2 - Define programmatically the callbacks at C side and attach them to VM.
3 - Execute the requested user's command.
4 - Store the VM snapshot/image again at DB (binary format).



This is working really fine, no problems these years (as you noticed, lol). The problem we are facing now is when we try to define more words at the initial image.


If we modify the original embed.fth (let's name it embed_mod1.fth), adding a new word (2+) at line 1121:

```
: 1+ 1 + ;                  ( n -- n : increment a value  )
: 2+ 2 + ;                  ( n -- n : increment a value by 2  )
```

and generate a new base image:

```
# ./embed -o embed_mod1.blk embed_mod1.fth
FORTH META COMPILATION START 
COMPILATION COMPLETE
HOST:    3F42
TARGET:  1524
HEADER: 
  5000:     14     0  7FFF  2400   34C  8000     0    14  _______$L_______
  5010:      0  7FFF  2400  4689  4854   A0D   A1A  1524  _____$_FTH____$_
  5020:   68D5     1  1984     1   947  628D  601C  628D  _h______G__b_`_b
  5030:   631C  10DC  151A     0  7003  6461  4017  4100  _c_______pad_@_A
SAVING...DONE
STACK> <sp
```

Find attached both files (embed_mod1.fth & embed_mod1.blk)

[meta-compiler-mod1.zip](https://github.com/howerj/embed/files/4101631/meta-compiler-mod1.zip)


We are able to correctly load the callbacks and use this new word inside the system:

```
2 2+ .
4
```

Find attached the VM snapshot after doing the same (embed_mod1_after_run_2+.blk)
[embed_mod1_after_run_2+.zip](https://github.com/howerj/embed/files/4101653/embed_mod1_after_run_2%2B.zip)

If we go an step forward and define a new word at base image (new file embed_mod2.fth), lets say that we add the word (3+) at line 1122:

```
: 1+ 1 + ;                  ( n -- n : increment a value  )
: 2+ 2 + ;                  ( n -- n : increment a value by 2  )
: 3+ 3 + ;                  ( n -- n : increment a value by 3 )
```

And generate a new base image:

```
# ./embed -o embed_mod2.blk embed_mod2.fth
FORTH META COMPILATION START 
COMPILATION COMPLETE
HOST:    3F50
TARGET:  152E
HEADER: 
  5000:     14     0  7FFF  2400   351  8000     0    14  _______$Q_______
  5010:      0  7FFF  2400  4689  4854   A0D   A1A  152E  _____$_FTH____._
  5020:   5CBB     1  1984     1   94C  628D  601C  628D  _\______L__b_`_b
  5030:   631C  10E6  1524     0  7003  6461  4017  4100  _c__$____pad_@_A
SAVING...DONE
STACK> <sp
```

Find attached both files (embed_mod2.fth & embed_mod2.blk)

[meta-compiler-mod2.zip](https://github.com/howerj/embed/files/4101639/meta-compiler-mod2.zip)


After adding this second word we are not able to run more commands, the callback loading fails as follows (these are our internal traces describing the problem):

```
* 23/01/2020,06:17:20.971 [0] ERROR: evaluation of statement (: perform 0 vm ; -2 cells allot ' vm chars ,
) returned -1
* 23/01/2020,06:17:20.971 [0] ERROR: unable to add VM callbacks
```

And the code executed there is the following (I think that is just a copy of your examples):

```
static int vm_add_callbacks(VirtualMachine_t* const vm, const bool optimize,  VmExtensionCb_t *cb, const size_t number) 
{
  // input pointers checked by calling function
  //assert(vm && cb);

  const char *optimizer = optimize ? "-2 cells allot ' vm chars ," : "";
  static const char *preamble = "only forth definitions system +order\n";
  int r = 0;

  if((r = embed_eval(vm, preamble)) < 0) {
    engine_trace(TRACE_LEVEL_ALWAYS, "ERROR: evaluation of preamble (%s) returned %d", preamble, r); 
    return r;
  }

  for(size_t i = 0; i < number; i++) {
    char line[80] = { 0 };
    if(!cb[i].use)
      continue;
    r = snprintf(line, sizeof(line), ": %s %u vm ; %s\n", cb[i].name, (unsigned)i, optimizer);
    assert(strlen(line) < sizeof(line) - 1);
    if(r < 0) {
      engine_trace(TRACE_LEVEL_ALWAYS, "ERROR: format error in snprintf (returned %d)", r); 
      return -1;
    }
    if((r = embed_eval(vm, line)) < 0) {
      engine_trace(TRACE_LEVEL_ALWAYS, "ERROR: evaluation of statement (%s) returned %d", line, r); 
      return r;
    }

    engine_trace(TRACE_LEVEL_ALWAYS, "Callback (%s) added to VM", cb[i].name); 
  }
  embed_reset(vm);
  return 0;
}
```

If we go back to the previous image (with only 1 extra word at meta-data, no problems at all with 3 callbacks).

If we remove some callbacks, the problem persists, we are not able to load callbacks with a base image that contains more than 1 extra word.

So our overall conclusion is that there is an space/size limit in the number of words + callbacks defined, and would like to know the value or increase it if feasible.

Please let me know if something else is required from our side. 

Find also attached the code where we manage VM and VM extensions (our interface with embed).



[source_code_using_embed.zip](https://github.com/howerj/embed/files/4101688/source_code_using_embed.zip)

The key function at vm.c is **vm_new(int agent_id)** and the vm_extensions file contains all extra logic we program at callbacks, not relevant I think but handy to help you with this.

**Comment by howerj** [comment]
Thanks for the detailed response.

Ok, so looking at this a bit more, it does appear that the system is
running out of memory during meta-compilation. This is not actually going
to be a problem for you, as there is another way that you can generate
an image you want. However I will explain what is going on, the easiest
way to resolve this, and other ways to resolve this. Also of note; I do
not think you should necessarily update to the latest version of the
embed interpreter - the latest version is not necessarily and better
than the version you have, in fact I may make breaking changes to it.

I should have noticed this earlier, it sometimes occurs to me when I am
modifying the base image (although I usually get different errors). You can see
the memory used during meta-compilation in this message here:

	FORTH META COMPILATION START 
	COMPILATION COMPLETE
	HOST:    3F50
	TARGET:  152E
	... (stuff)
	SAVING...DONE
	STACK> <sp

Where it says in hexadecimal '3F50', which is very close the end of memory
where the stacks are stored. The reason this is so high is because we are using
a Forth image running in the embed VM to generate a new Forth image. As such it
has to store the word set its own base image and the new target base image (we
can see the memory in the target image as being '152E' - so we have plenty of
room in the target. So if make a cross compiled word in the target, we have to
make one in the host, but we also have to keep a hold of other information
which means the meta-compiler runs out of memory here. There are a few ways to
resolve this:

1. You could delete unneeded words in 'embed.fth'. There are a lot of words that
you simply do not need for your game VM. Do you really need the block editor
word set? You do not need the CRC checks either, or the word 'see'. While we
have room in the target image we are creating, you would delete these words to
save space in the meta-compiler.
2. You could add your words after image generation. This is what you do with the
callbacks, you could just do it with these words.

So if you do this:

	$ cat >> my_own_words.fth
	: 1+ 1 + ;
	: 2+ 2 + ;
	: 3+ 3 + ;
	save
	bye
	$ ./embed -o 1.blk embed.fth
	$ ./embed -o 2.blk -i 1.blk my_own_words.fth

The new image '2.blk' contains the Forth words you want. You can also define
the Forth section of the VM callbacks you want to use within
'my\_own\_words.fth' (I assume you meant you only defined the words once when
you said you "Define programmatically the callbacks at C side and attach 
them to VM." otherwise you will run into problems).

3. There is no way of increasing the memory available *directly* to the virtual
machine without redesigning it. There are ways of increasing the available
memory *indirectly* however, but you will not want to do that and would only be
useful for data and new word definitions so it does not help you here.
4. You could do both steps '1.' and '2.' as there are words available to the
player that they probably do not need to have access to and would make more
memory available.

I think you should take the second approach, modifying the base image directly
in 'embed.fth' is probably more involved that you want.

Thanks,
Richard Howe

**Comment by darozak** [comment]
Hi Richard and Carlos. Thanks for working this out.  Your explanations make a ton of sense.  I'm sure that we can make solutions one and two work for us now that we know what's happening.  I agree that there are a lot of words in the current fth that won't be needed in the context of the game.  Thank you!

**Comment by howerj** [comment]
Great! If that's everything I'll close the issue?

**Comment by crodnun** [comment]
Yes. Go ahead

**Comment by crodnun** [comment]
Thank a lot for your kind suppot

**Comment by howerj** [comment]
Thanks!
